name: peek_and_pop
description: Peek & Pop implementation for Flutter based on the iOS functionality of the same name.
version: 0.1.2
author: Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository: https://github.com/aliyigitbireroglu/flutter-peek-and-pop
homepage: https://www.cosmossoftware.coffee

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

