name: example
description: Example Project for peek_and_pop.
version: 1.0.0+7
author: Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository: https://github.com/aliyigitbireroglu/flutter-peek-and-pop
homepage: https://www.cosmossoftware.coffee

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  peek_and_pop:
    path: ../
  snap: ^0.1.0
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.10+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Hero.png
    - assets/Scenery.jpeg
